import { useState, useEffect } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Mail, Phone, MapPin } from "lucide-react"
import { useUser, useClerk } from "@clerk/nextjs";
import { useSearchParams } from "next/navigation";
import { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

import { Geist, Geist_Mono } from 'next/font/google'
import { toast } from 'sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export function Contact() {
  const searchParams = useSearchParams();
  const showSent = searchParams.get("sent");
  const contactInfo = [
    {
      icon: <Mail className="h-6 w-6 text-primary" />,
      title: "Email",
      value: "hello@neobaus.com",
      href: "mailto:hello@neobaus.com"
    },
    {
      icon: <Phone className="h-6 w-6 text-primary" />,
      title: "Phone",
      value: "+63 (555) 123-4567",
      href: "tel:+15551234567"
    },
    {
      icon: <MapPin className="h-6 w-6 text-primary" />,
      title: "Location",
      value: "Caloocan City, Philippines, Metro Manila",
      href: "https://maps.google.com/?q=Manila,Philippines"
    }
  ]

  const { user } = useUser();
  const name = user ? `${user.firstName || ''} ${user.lastName || ''}`.trim() : '';
  const email = user?.emailAddresses[0]?.emailAddress || '';

  const [message, setMessage] = useState("");
  const [status, setStatus] = useState(null); // null | 'sending' | 'success' | 'error'
  const [removeStatus, setRemoveStatus] = useState(null); // null | 'pending' | 'done' | 'error'

  useEffect(() => {
    if (showSent && !user) {
      toast.success("Message sent! We'll get back to you soon.", { duration: 15000 });
    }
  }, [showSent, user]);

  const { signOut } = useClerk();

  async function handleSubmit(e) {
    e.preventDefault();

    if (!user) {
      // Don't submit if user is not signed in.
      return;
    }

    setStatus("sending");

    try {
      const res = await fetch("/api/contact", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name,
          email,
          message,
        }),
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || "Failed to send message");
      }

      setStatus("success");
      setMessage("");
      // Logout and redirect to /contact?sent=1
      await signOut({ redirectUrl: "/contact?sent=1" });
    } catch (err) {
      console.error(err);
      setStatus("error");
    }
  }

  return (
    <section id="contact" className="py-12 sm:py-16 lg:py-20 bg-muted/30">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-8 sm:mb-12 lg:mb-16">
          <Badge variant="outline" className="mb-3 sm:mb-4 text-lg">
            Contact Us
          </Badge>
          <h2 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-foreground mb-3 sm:mb-4">
            Get in Touch
          </h2>
          <p className="text-base sm:text-lg text-muted-foreground max-w-2xl mx-auto px-4">
            Have a question or want to work together? We'd love to hear from you.
          </p>
        </div>
        

        <div className="max-w-4xl mx-auto">
          {/* <div className="grid grid-cols-1 md:grid-cols-3 gap-4 sm:gap-6 mb-8">
            {contactInfo.map((info, index) => (
              <a
                key={index}
                href={info.href}
                target="_blank"
                rel="noopener noreferrer"
                className="block group"
              >
                <Card className="h-full hover:shadow-lg transition-all duration-300 group-hover:-translate-y-1">
                  <CardHeader className="text-center">
                    <div className="mx-auto mb-3 transform transition-transform duration-300 group-hover:scale-110">
                      {info.icon}
                    </div>
                    <CardTitle className="text-lg mb-2">{info.title}</CardTitle>
                  </CardHeader>
                  <CardContent className="text-center text-muted-foreground">
                    {info.value}
                  </CardContent>
                </Card>
              </a>
            ))}
          </div> */}

          <Card className="overflow-hidden">
            <CardHeader className="text-center pb-0">
              <CardTitle className="text-xl sm:text-2xl mb-0">Send us a Message</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <SignedOut>
                <div className="text-center">
                  <SignInButton redirecturl="/contact" aschild='true'>
                    <button className="bg-[#6c47ff] text-ceramic-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer ml-2">
                      Securely send us a message
                    </button>
                  </SignInButton>
                </div>
              </SignedOut>
              <SignedIn>
                <form className="space-y-4" onSubmit={handleSubmit}>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium mb-1">Name</label>
                      <input
                        type="text"
                        value={name}
                        disabled
                        className="w-full px-3 py-2 border rounded-md bg-background/50"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium mb-1">Email</label>
                      <input
                        type="email"
                        value={email}
                        disabled
                        className="w-full px-3 py-2 border rounded-md bg-background/50"
                      />
                    </div>
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-1">Message</label>
                    <textarea
                      className="w-full px-3 py-2 border rounded-md bg-background"
                      rows={4}
                      value={message}
                      onChange={(e) => setMessage(e.target.value)}
                      required
                      placeholder="Your message here..."
                    ></textarea>
                  </div>
                  <div className="flex flex-row justify-end items-center gap-4 mt-4">
                    <Button type="submit" size="lg" disabled={status === "sending"}
                      >
                      {status === "sending" ? "Sending..." : "Send Message"}
                    </Button>
                    <UserButton className="ml-0" />
                  </div>
                  {status === "error" && <p className="text-sm text-red-600">Something went wrong. Please try again later.</p>}
                </form>
              </SignedIn>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
}